### PR TITLE
Add missing numpy import

### PR DESCRIPTION
**Pull request by shane-powell**
Found numpy was a missing required import while setting up my weather station.

You may need to update the website tutorial docs if they are not generated from this.

### CODE REVIEW

**Comment by shane-powell** [comment]
I found I also needed to install libatlas-base-dev for weather.py to work. Is the tutorial for the full OD? I am using the lite version which is the one I would imagine people would usually pick as its likely going to be headless?

If so it could be worded that these are the extra steps required for a lite install.

**Comment by Gadgetoid** [comment]
> Is the tutorial for the full OD? I am using the lite version which is the one I would imagine people would usually pick as its likely going to be headless?

Ugh, yes it is. Wouldn't be the first or second time the differences have bitten us. Well spotted!

Summoning :candle: @helgibbons :candle: to tweak tutorial as required!

**Comment by shane-powell** [comment]
> Thanks Shane - I've made the recommendation to use Full/Desktop Pi OS more explicit in the tutorial, and added a bit of guidance for folks using Lite.
> 
> https://learn.pimoroni.com/article/getting-started-with-weather-hat

No worries!

Ah yes I forgot to mention needing to install git.

I guess I did that subconsciously. 😂

**Comment by Gadgetoid** [comment]
Thank you all!

**Pull request merged**
